image: docker/compose:latest

services:
  - docker:dind

before_script:
  - docker version
  - docker-compose version

stages:
  - staging

staging:
  stage: staging
  script:
    - docker-compose -f docker-compose.yml --env-file docker/.env.staging up -d --build --force-recreate
    - docker exec laravel-app composer install --no-interaction
  environment:
    name: staging
  only:
    - branches
  except:
    - master
